"""Add game_user Association Table

Revision ID: b1e8ad0a8449
Revises: b96db01668df
Create Date: 2023-06-25 18:46:45.469860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e8ad0a8449'
down_revision = 'b96db01668df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
